import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import BeforeAfter from "./_components/BeforeAfter";
import Cards from "./_components/Cards";
import FAQ from "./_components/Faq";
import Footer from "./_components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${geistSans.className}`}
      >
        <div className="md:px-20">
          <Header></Header>
          <BeforeAfter></BeforeAfter>
          <Cards></Cards>
          <FAQ></FAQ>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
